replicaCount: 1
image:
  repository: registry.alexshangin.ru/sim_info
  pullPolicy: IfNotPresent
  tag: f499e4c
imagePullSecrets:
  - name: alexshangin
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: public
  annotations:
    external-dns.alpha.kubernetes.io/access: public
    external-dns.alpha.kubernetes.io/hostname: sim.office.ru.
    external-dns.alpha.kubernetes.io/target: kube1.office.ru.
    ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'false'
  hosts:
    - host: sim.office.ru
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: sim.s-globus.ru
      paths:
        - path: /
          pathType: ImplementationSpecific
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
