name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set Image
        run: echo "DOCKER_IMAGE=${{ secrets.REGISTRY_URL }}/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        
      - name: Set Tag
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}, ${{ env.DOCKER_IMAGE }}:latest
          cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ env.DOCKER_IMAGE }}:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ env.DOCKER_IMAGE }},mode=max'
      
      - name: Update Docker repository
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '.helm/values.yaml'
          propertyPath: 'image.repository'
          value: ${{ env.DOCKER_IMAGE }}
          updateFile: true
          message: 'Update Repository to ${{ env.DOCKER_IMAGE }}'
          
      - name: Update Image Tag
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '.helm/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ env.DOCKER_TAG }}
          updateFile: true
          message: 'Update Tag to ${{ env.DOCKER_TAG }}'
    
